### ISSUE TITLE
How about using C STD uint32_t instead of puint32 and so on?

### ISSUE THREAD

**Issue by lygstate** [saprykin/plibsys#87] opened 2020-08-28 03:57 UTC

**Comment by saprykin** [comment] 2020-08-30 11:33
Well, the problem is that on some operating systems a compiler can be rather old (i.e. GCC < 3.x) or non-compliant with C99 standard which introcuced fixed integer types. That's the reason why we have to use custom data types - to insure that everything is consistent and portable across a wide range of systems and compilers.

**Closed** 2020-12-20 22:45 UTC
